# Generated by Django 5.1.6 on 2025-04-06 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_responder_assigned_emergencies'),
        ('emergencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencies', to='core.responder'),
        ),
    ]
