# Generated by Django 5.1.6 on 2025-04-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
