# Generated by Django 5.1.6 on 2025-04-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0002_emergency_responder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='reported', max_length=20),
        ),
    ]
