# Generated by Django 5.1.6 on 2025-04-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0003_alter_emergency_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('acknowledged', 'Acknowledged'), ('en_route', 'En Route'), ('on_site', 'On_Site'), ('resolved', 'Resolved')], default='reported', max_length=20),
        ),
    ]
