# Generated by Django 5.1.6 on 2025-04-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0003_remove_emergency_location_remove_emergency_reporter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('threat_level', models.CharField(choices=[('high', 'High Threat'), ('medium', 'Medium Threat'), ('low', 'Low Threat')], default='medium', max_length=20)),
                ('incident_count', models.PositiveIntegerField(default=0)),
                ('last_incident', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-threat_level', '-last_incident'],
            },
        ),
    ]
