# Generated by Django 5.1.6 on 2025-04-05 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emergencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responder_status', models.CharField(choices=[('Available', 'Available'), ('Engaged', 'Engaged')], default='Available', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_emergency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_responders', to='emergencies.emergency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responder_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
