# Generated by Django 5.1.6 on 2025-04-09 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responder_status', models.CharField(choices=[('available', 'Available'), ('engaged', 'Engaged')], default='available', max_length=10)),
                ('emergency_category', models.CharField(blank=True, choices=[('unassigned', 'Unassigned'), ('health', 'Health'), ('security', 'Security'), ('fire', 'Fire')], default='unassigned', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responder_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
