# Generated by Django 5.1.6 on 2025-04-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responder',
            old_name='assigned_emergency',
            new_name='assigned_emergencies',
        ),
        migrations.AddField(
            model_name='responder',
            name='emergency_category',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('health', 'Health'), ('security', 'Security'), ('fire', 'Fire')], default='unassigned', max_length=10),
        ),
        migrations.AlterField(
            model_name='responder',
            name='responder_status',
            field=models.CharField(choices=[('available', 'Available'), ('engaged', 'Engaged')], default='available', max_length=10),
        ),
    ]
