# Generated by Django 5.1.6 on 2025-04-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_assigned_emergency_responder_assigned_emergencies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responder',
            name='emergency_category',
            field=models.CharField(blank=True, choices=[('unassigned', 'Unassigned'), ('health', 'Health'), ('security', 'Security'), ('fire', 'Fire')], default='unassigned', max_length=10),
        ),
    ]
