# Generated by Django 5.1.6 on 2025-04-06 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_responder_emergency_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responder',
            name='assigned_emergencies',
        ),
    ]
